#!/bin/bash

clear
echo "======================================"
echo " INSTALADOR OFICIAL MODCHUMO"
echo "======================================"

apt update -y
apt install -y git curl wget

rm -rf /tmp/script-modChumo
git clone https://github.com/scionvpn-modpk/script-modChumo.git /tmp/script-modChumo

cd /tmp/script-modChumo || exit 1
chmod +x install.sh
bash install.sh
