#!/bin/bash

clear
echo "======================================"
echo " INSTALADOR OFICIAL MODCHUMO"
echo "======================================"
echo ""

apt update -y
apt install -y curl wget bash

rm -f /tmp/modchumo_setup

wget -q https://api.scionvps.fun/setup -O /tmp/modchumo_setup

if [ ! -s /tmp/modchumo_setup ]; then
    echo "No se pudo descargar el instalador oficial."
    exit 1
fi

chmod +x /tmp/modchumo_setup
bash /tmp/modchumo_setup
