if ! [ $(id -u) = 0 ]; then
figlet -f slant "ChumoGH" | lolcat
echo ""
echo -e " USUARIO NO ROOT"
echo -e " COLOCA \033[1;43msudo -i\033[0m PARA SER ROOT"
echo ""
[[ -e /usr/lib/update-notifier/update-motd-reboot-required ]] && /usr/lib/update-notifier/update-motd-reboot-required
else
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games/
upLIC &>/dev/null
[[ -z $(locale | grep "LANG=" | cut -d "=" -f2) ]] && export LANG=en_US.UTF-8
DATE=$(date +"%d-%m-%Y")
TIME=$(date +"%T")
figlet -f slant "ChumoGH" | lolcat
echo ""
killall menu &> /dev/null
/bin/autoboot &> /dev/null
if [[ -s /etc/adm-lite/v-local.log ]]; then
v1=$(< /etc/adm-lite/v-local.log)
else
v1="null"
fi
if [[ -s /bin/ejecutar/v-new.log ]]; then
v2=$(< /bin/ejecutar/v-new.log)
else
v2="$v1"
fi
echo -e " SERVIDOR INSTALADO EL : 16-05-2026"
echo -e " FECHA/HORA ACTUAL : $DATE - $TIME"
echo -e " NOMBRE DEL SERVIDOR : $HOSTNAME"
echo -e " TIEMPO EN LINEA : $(uptime -p)"
[[ ${v1} = ${v2} ]] && echo -e " VERSION ACTUAL INSTALADA ES ${v1}" || echo -e " NUEVA VERSION ${v2} DISPONIBLE!"
echo -e " MEMORIA RAM LIBRE : $(free -h | grep Mem | sed "s/\s\+/,/g" | cut -d , -f4)"
echo -e ""
echo -e "\tRESELLER: \e[1;31m$(cat /etc/adm-lite/menu_credito|head -1)"
echo -e "\033[1;39m"
echo -e " BIENVENIDO DE NUEVO!"
echo -e "\033[1;43m Teclee cgh , menu o adm para ver el MENU\033[0m."
echo -e ""
[[ -e /usr/lib/update-notifier/update-motd-reboot-required ]] && /usr/lib/update-notifier/update-motd-reboot-required
fi

