#!/bin/bash
#CREADOR Henry Chumo | 06/06/2019
# UPDATE DEFINIDO    | 26/10/2023
#Alias : @ChumoGH

# NUNCA  DEJES DE APRENDER
# POWER BY @CHUMOGH

# -*- ENCODING: UTF-8 -*-
z="
";XUz='clone your fucking mother'
@Generadormx_bot|2087504514:AAGEm4yEACximf6fNfOKxf2eZBOWTeNkZHI|@ANTONIOMXR7
